name: agentic
description: Ai Wrapper
version: 1.0.0
repository: https://github.com/ArcaneArts/agentic
environment:
  sdk: ^3.7.0
dependencies:
  artifact: ^1.0.12
  decimal: ^3.2.1
  rational: ^2.2.3
  toxic: ^1.3.4
  langchain: ^0.7.7+2
  langchain_core: ^0.3.6+1
  langchain_tiktoken: ^1.0.1
  langchain_google: ^0.6.4+2
  langchain_openai: ^0.7.3
  langchain_anthropic: ^0.2.0+1
dev_dependencies:
  artifact_gen: ^1.0.8
  build_runner: ^2.4.15
  lints: ^5.1.1
  test: ^1.25.15
scripts:
  build: dart run build_runner build --delete-conflicting-outputs