name: agentic
description: Ai Wrapper
version: 1.0.9
repository: https://github.com/ArcaneArts/agentic
environment:
  sdk: ^3.7.0
dependencies:
  artifact: ">=1.0.14 <2.0.0"
  decimal: ">=3.2.1 <4.0.0"
  rational: ">=2.2.3 <3.0.0"
  toxic: ">=1.3.4 <2.0.0"
  langchain: ">=0.7.7 <1.0.0"
  langchain_core: ">=0.3.6 <1.0.0"
  langchain_google: ">=0.6.4 <1.0.0"
  langchain_openai: ">=0.7.3 <1.0.0"
  langchain_anthropic: ">=0.2.0 <1.0.0"
  yaml_edit: ">=2.2.2 <3.0.0"
  mcp_dart: ">=0.5.0 <1.0.0"
  fast_log: ^1.0.7
dev_dependencies:
  artifact_gen: ^1.0.13
  build_runner: ^2.4.15
  lints: ^5.1.1
  test: ^1.25.15
scripts:
  build: dart run build_runner build --delete-conflicting-outputs